name: "Dali2IoT 2 MQTT gateway"
description: "My first real add-on!"
version: "1.0.5"
slug: "dali2iot2mqtt"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
options:
  mqtt_host: ""
  mqtt_port: ""
  mqtt_user: ""
  mqtt_pass: ""
  dali_2_iot_host: ""
schema:
  mqtt_host: str
  mqtt_port: str
  mqtt_user: str
  mqtt_pass: str
  dali_2_iot_host: str